version: "3.7"

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: PROYECTO_BASE_FRONTEND
    restart: always
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - proyecto_base_net

networks:
  proyecto_base_net:
    








# version: '3'
# services:
#   frontend:
#     build:
#       context: ..
#       dockerfile: docker/Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - ../:/app
#       - /app/node_modules
#     stdin_open: true
#     tty: true
#     environment:
#       - NODE_ENV=development
#     networks:
#       - proyecto_base_net

# networks:
#   proyecto_base_net:
#     external: true